# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firstStack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firstStack
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'firstStackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firstStack-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firstStack-tvOS

  target 'firstStack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
